apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: mother-of-bots
data:
  gcp_project_id: "motherofbots"
  gcp_location: "us-central1"
  gemini_model: "gemini-2.5-flash"
  api_port: "5000"
  gcs_bucket_name: "motherofbots-generated-projects"

