apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  labels:
    app: mother-of-bots
  annotations:
    iam.gke.io/gcp-service-account: mob-653@motherofbots.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  labels:
    app: mother-of-bots

